/* Mock data for the Banket UI kit — mirrors the production screenshots. */
window.BK_DATA = {
  user: { name: "Leandro", role: "Proprietário" },
  stages: [
    { key: "new", label: "Novo orçamento", fn: "Entrada (novos pedidos)" },
    { key: "negotiation", label: "Em negociação", fn: "Em andamento" },
    { key: "won", label: "Aprovado", fn: "Ganho (aprovado)" },
    { key: "lost", label: "Recusado", fn: "Perdido (recusado)" },
  ],
  events: [
    { id: 1, title: "Degustação", full: "Degustação 4 – Maria Eduarda Silva", client: "Maria Eduarda Silva", kind: "person", stage: "new", type: "Social", pessoas: "50", formato: "-", verba: "-", data: "19/11/2026", dias: "há 11 dias nesta etapa" },
    { id: 2, title: "Casamento", full: "Casamento – Antonio Rodrigues Neto", client: "Antonio Rodrigues Neto", kind: "person", stage: "new", type: "Social", pessoas: "77", formato: "Ilhas gastronômicas", verba: "-", data: "12/11/2026", dias: "há 10 dias nesta etapa" },
    { id: 3, title: "Degustação", full: "Degustação 3 – Maria Eduarda Silva", client: "Maria Eduarda Silva", kind: "person", stage: "new", type: "Social", pessoas: "50", formato: "-", verba: "-", data: "12/11/2026", dias: "há 11 dias nesta etapa" },
    { id: 4, title: "Evento – E2E Mobile 1790615118390", full: "Evento – E2E Mobile 1790615118390", client: "E2E Mobile 1790615118390", kind: "person", stage: "new", pessoas: "-", formato: "-", verba: "-", data: "-", dias: "há 5 dias nesta etapa" },
    { id: 5, title: "Degustação", full: "Degustação 1 – Maria Eduarda Silva", client: "Maria Eduarda Silva", kind: "person", stage: "negotiation", type: "Social", pessoas: "50", formato: "-", orcamento: "R$ 9.250,00", data: "29/10/2026", dias: "há 11 dias nesta etapa" },
    { id: 6, title: "Degustação", full: "Degustação 2 – Maria Eduarda Silva", client: "Maria Eduarda Silva", kind: "person", stage: "negotiation", type: "Social", pessoas: "50", formato: "-", orcamento: "R$ 4.250,00", data: "05/11/2026", dias: "há 11 dias nesta etapa" },
    { id: 7, title: "Casamento", full: "Casamento – Maria Eduarda Silva", client: "Maria Eduarda Silva", kind: "person", stage: "negotiation", type: "Social", pessoas: "150", formato: "-", orcamento: "R$ 25.500,00", data: "15/11/2026", dias: "há 11 dias nesta etapa" },
    { id: 8, title: "Confraternização de fim de ano", full: "Confraternização de fim de ano – TechCorp Brasil", client: "TechCorp Brasil", kind: "company", stage: "negotiation", type: "Corporativo", pessoas: "300", formato: "-", orcamento: "R$ 42.000,00", data: "10/12/2026", dias: "há 11 dias nesta etapa" },
    { id: 9, title: "Festa de 15 Anos", full: "Festa de 15 Anos – João Pedro Oliveira", client: "João Pedro Oliveira", kind: "person", stage: "negotiation", type: "Social", pessoas: "200", formato: "-", orcamento: "R$ 18.000,00", data: "20/02/2027", dias: "há 11 dias nesta etapa" },
    { id: 10, title: "Aniversário", full: "Aniversário – Pestana", client: "Pestana", kind: "person", stage: "negotiation", type: "Social", pessoas: "50", formato: "Empratado", orcamento: "R$ 9.200,00", data: "20/03/2027", dias: "há 10 dias nesta etapa" },
    { id: 11, title: "Confraternização de Final de Ano TCBr", full: "Confraternização de Final de Ano TCBr", client: "TechCorp Brasil", kind: "company", stage: "won", type: "Corporativo", pessoas: "540", formato: "Serviço volante", orcamento: "R$ 8.500,00", data: "10/01/2027", dias: "há 11 dias nesta etapa" },
  ],
  clients: [
    { id: 1, nome: "Antonio Rodrigues Neto", doc: "-", email: "antonio-rn@live.com", tel: "(49) 98877-6621", eventos: 1 },
    { id: 2, nome: "Bruno Carvalho Pinto", doc: "-", email: "bruno.pinto@exemplo.com.br", tel: "(11) 98888-7777", eventos: 0 },
    { id: 3, nome: "Camila Rocha Nogueira", doc: "-", email: "camila.nogueira@exemplo.com.br", tel: "(11) 98888-7777", eventos: 0 },
    { id: 4, nome: "Fernanda Almeida Santos", doc: "123.456.789-00", email: "fernanda.santos@email.com", tel: "(41) 99123-4567", eventos: 1 },
    { id: 5, nome: "João Pedro Oliveira", doc: "-", email: "joao.oliveira@email.com", tel: "(41) 98765-4321", eventos: 1 },
    { id: 6, nome: "Maria Eduarda Silva", doc: "987.654.321-00", email: "maria.eduarda@email.com", tel: "(41) 99999-1234", eventos: 6 },
    { id: 7, nome: "TechCorp Brasil", doc: "12.345.678/0001-90", email: "eventos@techcorp.com.br", tel: "(11) 3333-4444", eventos: 2 },
  ],
  menuOptions: [
    { id: 1, title: "Brunch", preco: "R$ 250,00", duracao: "2 horas", secoes: "09", itens: "46", tags: ["Buffet", "Brunch"] },
    { id: 2, title: "Buffet – Opção 01", preco: "R$ 80,00", duracao: "-", secoes: "08", itens: "31", tags: ["Buffet"] },
    { id: 3, title: "Buffet – Opção 02", preco: "R$ 105,00", duracao: "-", secoes: "10", itens: "52", tags: ["Buffet"] },
    { id: 4, title: "Buffet – Opção 03", preco: "R$ 140,00", duracao: "-", secoes: "10", itens: "61", tags: ["Buffet", "Premium"] },
    { id: 5, title: "Comida de boteco", preco: "R$ 110,00", duracao: "2 horas", secoes: "02", itens: "09", tags: ["Serviço volante", "Boteco", "Informal"] },
    { id: 6, title: "Coquetel de Boas-Vindas", preco: "R$ 45,90", duracao: "-", secoes: "01", itens: "06", tags: [] },
    { id: 7, title: "Coquetel recepção – Opção 01", preco: "R$ 25,00", duracao: "-", secoes: "01", itens: "03", tags: ["Serviço volante", "Coquetel", "Casamento"] },
    { id: 8, title: "Empratado – Opção 01 (1 prato principal)", preco: "R$ 160,00", duracao: "-", secoes: "03", itens: "14", tags: ["Empratado", "Jantar"] },
  ],
  menuItems: [
    { id: 1, nome: "Pão de fermentação natural", desc: "-", secao: "Mesa de pães", preco: "-", cat: "Salgado" },
    { id: 2, nome: "Croissant", desc: "-", secao: "Mesa de pães", preco: "-", cat: "Salgado" },
    { id: 3, nome: "Salame italiano", desc: "-", secao: "Queijos e embutidos", preco: "-", cat: "Salgado" },
    { id: 4, nome: "Croissant com copa", desc: "Croissant, copa, parmesão, alface, tomate e molho rosé", secao: "Sanduíches", preco: "-", cat: "Salgado" },
    { id: 5, nome: "Focaccia caprese", desc: "Focaccia, muçarela de búfala, tomate, rúcula e pesto", secao: "Sanduíches", preco: "-", cat: "Salgado" },
    { id: 6, nome: "Burrata", desc: "Burrata acompanhada de tomates frescos e pesto de manjericão", secao: "Antepastos", preco: "-", cat: "Salgado" },
    { id: 7, nome: "Brie assado", desc: "Brie assado com castanhas, nozes e mel", secao: "Antepastos", preco: "-", cat: "Salgado" },
    { id: 8, nome: "Batatas confitadas", desc: "Batatas confitadas com alho, pimenta dedo-de-moça e alecrim", secao: "Antepastos", preco: "-", cat: "Salgado" },
  ],
  sections: [
    { id: 1, nome: "Mesa de pães", itens: 3, opcoes: 3 }, { id: 2, nome: "Queijos e embutidos", itens: 3, opcoes: 3 },
    { id: 3, nome: "Sanduíches", itens: 2, opcoes: 1 }, { id: 4, nome: "Antepastos", itens: 16, opcoes: 3 },
    { id: 5, nome: "Quiches, tortas e massas do brunch", itens: 4, opcoes: 1 }, { id: 6, nome: "Frutas, caldas e geleias", itens: 5, opcoes: 2 },
    { id: 7, nome: "Coquetel", itens: 7, opcoes: 6 }, { id: 8, nome: "Saladas", itens: 7, opcoes: 5 },
  ],
  categories: [
    { id: 1, nome: "Salgado", aplica: "Principal (tipo)" }, { id: 2, nome: "Doce", aplica: "Principal (tipo)" }, { id: 3, nome: "Bebida", aplica: "Principal (tipo)" },
    { id: 4, nome: "Recepção", aplica: "Secundária (momento)" }, { id: 5, nome: "Entrada", aplica: "Secundária (momento)" }, { id: 6, nome: "Prato principal", aplica: "Secundária (momento)" }, { id: 7, nome: "Sobremesa", aplica: "Secundária (momento)" },
  ],
  users: [
    { id: 1, nome: "Leandro (você)", email: "leandro@banket.com.br", papel: "Proprietário", self: true },
    { id: 2, nome: "Operação Demo", email: "operacao@banket.com.br", papel: "Usuário" },
    { id: 3, nome: "Pestana", email: "pestana@banket.com.br", papel: "Proprietário" },
  ],
};
